### ISSUE TITLE
Merging lists removes duplicate entries

### ISSUE THREAD

**Issue by Parakoopa** [Parakoopa/configcrunch#1]
When Configcrunch merges lists, and the list to append contains values, that are already in the parent document's list, the duplicate entries are removed.

### Steps to Reproduce:
- Have two documents that look like this:
```yaml
# doc1.yml
doc:
  $ref: /doc2
  list:
    - a
    - c
```
```yaml
# doc2.yml
doc:
  list:
    - a
    - b
```
- Merge them with `doc1.yml` as entrypoint, and a lookup path containing `doc2.yml`.

### Expected Result:
```yaml
doc:
  list:
    - a
    - b
    - a
    - c
```

### Actual Result:
```yaml
doc:
  list:
    - a
    - b
    - c
```
